---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: scalingredis-example
spec:
  replicas: 3
  selector:
    matchLabels:
      name: scalingredis-example-api
      app: examples
      tier: api
  template:
    metadata:
      name: scalingredis-example-api
      labels:
        name: scalingredis-example-api
        app: examples
        tier: api
    spec:
      containers:
      - name: scalingredis-ssl-tunnel
        imagePullPolicy: Always
        image: gronnbeck/redis-compose-ssl-tunnel:latest
        volumeMounts:
        - name: scalingreach-compose-tunnel-cert
          mountPath: /var/cert
          readOnly: true
        env:
          - name: REDIS_SSL_TUNNEL_HOST
            valueFrom:
              secretKeyRef:
                name: scalingredis-compose-tunnel
                key: host
          - name: REDIS_SSL_TUNNEL_PORT
            valueFrom:
              secretKeyRef:
                name: scalingredis-compose-tunnel
                key: port
          - name: REDIS_SSL_TUNNEL_DST_IP
            valueFrom:
              secretKeyRef:
                name: scalingredis-compose-tunnel
                key: dst_ip
          - name: REDIS_SSL_TUNNEL_SRC_PORT
            value: "7007"
      - name: scalingredis-api
        imagePullPolicy: Always
        image: gronnbeck/scalingredis:latest
        ports:
        - name: api
          containerPort: 8080
        env:
          - name: REDIS_ADDR
            value: localhost:6379
      - name: scalingredis-api-redis
        imagePullPolicy: Always
        image: gronnbeck/scalingredis-api-redis-slave:latest
        env:
          - name: REDIS_MASTER_URL
            value: "127.0.0.1"
          - name: REDIS_MASTER_PORT
            value: "7007"
          - name: REDIS_MASTER_PASS
            valueFrom:
              secretKeyRef:
                name: scalingredis-example-secret
                key: redis-pass
          - name: REDIS_PORT
            value: "6379"
      volumes:
      - name: scalingreach-compose-tunnel-cert
        secret:
          secretName: scalingreach-compose-tunnel-cert
---
kind: Service
apiVersion: v1
metadata:
  name: scalingredis-example-api
  labels:
    app: examples
spec:
  selector:
    name: scalingredis-example-api
    app: examples
    tier: api
  ports:
    - name: api
      protocol: TCP
      port: 8080
  type: LoadBalancer
